---
services: docker

env:
  # Test package install on all supported OSes.
  - distro: gallium
    playbook: test.yml
  - distro: xenial
    playbook: test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export test_suite=false

  # Run tests.
  - chmod +x ${PWD}/tests/run-test.sh
  - ${PWD}/tests/run-test.sh

  # Ensure blackfire is installed and working.
  - 'docker exec --tty ${container_id} env TERM=xterm which blackfire'
  - 'docker exec --tty ${container_id} env TERM=xterm test -x /usr/bin/blackfire'

  - 'docker exec --tty ${container_id} env TERM=xterm blackfire --version'
  - 'docker exec --tty ${container_id} env TERM=xterm /usr/bin/blackfire --version | grep -qF "$BLACKFIRE_VERSION"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/